"""initial_schema

Revision ID: d79806ac3566
Revises: 
Create Date: 2026-09-29 16:09:35.658626
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'd79806ac3566'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True, comment='vendor | buyer | admin | mixer | unknown'),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='active | dormant | merged | unknown'),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('actor_id', name=op.f('pk_actors'))
    )
    op.create_index('ix_actors_label', 'actors', ['label'], unique=False)
    op.create_index('ix_actors_status', 'actors', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False, comment='persona_migration | watchlist_hit | new_actor | infra_leak'),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False, comment='open | acknowledged | resolved | false_positive'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_type', 'alerts', ['alert_type'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False, comment="user_id or 'system'"),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_actor', 'audit_log', ['actor'], unique=False)
    op.create_index('ix_audit_at', 'audit_log', ['at'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False, comment='handle | pgp | wallet | email | domain | onion | contact_id | avatar_hash | ip | favicon_hash | cert_fp | ssh_key'),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('normalized', sa.String(length=1024), nullable=False, comment='Lowercased, stripped, canonical form for dedup'),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_entities')),
    sa.UniqueConstraint('kind', 'normalized', name='uq_entities_kind_normalized')
    )
    op.create_index('ix_entities_kind', 'entities', ['kind'], unique=False)
    op.create_index('ix_entities_normalized', 'entities', ['normalized'], unique=False)
    op.create_table('merkle_batches',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('root_hash', sa.String(length=71), nullable=False),
    sa.Column('leaf_count', sa.Integer(), nullable=False),
    sa.Column('anchor_ref', sa.String(length=256), nullable=True, comment='OpenTimestamps or testnet tx ref (stretch)'),
    sa.Column('anchor_type', sa.String(length=64), nullable=True, comment='opentimestamps | btc_testnet | eth_sepolia'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_merkle_batches'))
    )
    op.create_table('sources',
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='synthetic | replay | osint_feed | clearnet_intel | blockchain | discovery | lab | authorized'),
    sa.Column('collection_method', sa.String(length=256), nullable=True),
    sa.Column('authorization_status', sa.String(length=32), nullable=False, comment='approved | authorized | disabled'),
    sa.Column('authorization_ref', sa.String(length=512), nullable=True, comment="Required for 'authorized' sources — signed JWT reference"),
    sa.Column('permitted_use', sa.Text(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('pii_policy', sa.String(length=256), nullable=True),
    sa.Column('reliability_grade', sa.String(length=1), nullable=False, comment='Admiralty reliability: A-F'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(authorization_status != 'authorized') OR (authorization_ref IS NOT NULL)", name=op.f('ck_sources_authorized_needs_ref')),
    sa.CheckConstraint("authorization_status IN ('approved', 'authorized', 'disabled')", name=op.f('ck_sources_valid_auth_status')),
    sa.CheckConstraint("reliability_grade IN ('A', 'B', 'C', 'D', 'E', 'F')", name=op.f('ck_sources_valid_reliability_grade')),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_sources'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False, comment='viewer | analyst | admin'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='OWASP A07: track failed attempts for lockout'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='Account lockout after too many failed attempts'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'analyst', 'admin')", name=op.f('ck_users_valid_user_role')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('actor_entities',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=False, comment='system | analyst:<user_id>'),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], name=op.f('fk_actor_entities_actor_id_actors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], name=op.f('fk_actor_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id', 'entity_id', name=op.f('pk_actor_entities'))
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False, comment='live | replay | authorized'),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=71), nullable=False, comment='sha256:hex — also serves as dedup key'),
    sa.Column('payload_ref', sa.String(length=512), nullable=False, comment='s3://netra-snapshots/...'),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_events_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_events_content_hash'))
    )
    op.create_index('ix_events_content_hash', 'events', ['content_hash'], unique=False)
    op.create_index('ix_events_observed_at', 'events', ['observed_at'], unique=False)
    op.create_index('ix_events_source', 'events', ['source_id'], unique=False)
    op.create_table('infra_findings',
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('onion_entity', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False, comment='cert_san | favicon | banner | server_status | ssh_key | header_order | error_page'),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_clearnet', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['onion_entity'], ['entities.entity_id'], name=op.f('fk_infra_findings_onion_entity_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_infra_findings_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_infra_findings'))
    )
    op.create_index('ix_infra_onion', 'infra_findings', ['onion_entity'], unique=False)
    op.create_table('persona_links',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('actor_a', sa.String(length=36), nullable=False),
    sa.Column('actor_b', sa.String(length=36), nullable=False),
    sa.Column('link_type', sa.String(length=64), nullable=False, comment='persona_migration | shared_identity | co_operator | financial_link'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False, comment='VERY_HIGH | HIGH | MODERATE | LOW | WEAK'),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('analyst_status', sa.String(length=32), nullable=False, comment='pending | confirmed | rejected | needs_info'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analyst_status IN ('pending', 'confirmed', 'rejected', 'needs_info')", name=op.f('ck_persona_links_valid_analyst_status')),
    sa.CheckConstraint("band IN ('VERY_HIGH', 'HIGH', 'MODERATE', 'LOW', 'WEAK')", name=op.f('ck_persona_links_valid_band')),
    sa.CheckConstraint('actor_a != actor_b', name=op.f('ck_persona_links_no_self_link')),
    sa.ForeignKeyConstraint(['actor_a'], ['actors.actor_id'], name=op.f('fk_persona_links_actor_a_actors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_b'], ['actors.actor_id'], name=op.f('fk_persona_links_actor_b_actors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('link_id', name=op.f('pk_persona_links'))
    )
    op.create_index('ix_persona_links_actors', 'persona_links', ['actor_a', 'actor_b'], unique=False)
    op.create_index('ix_persona_links_band', 'persona_links', ['band'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True, comment='Null if blocked (no event created)'),
    sa.Column('rule_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('allow', 'block', 'redact_allow')", name=op.f('ck_policy_decisions_valid_decision')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_policy_decisions_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_policy_decisions'))
    )
    op.create_index('ix_policy_decisions_decided_at', 'policy_decisions', ['decided_at'], unique=False)
    op.create_index('ix_policy_decisions_source', 'policy_decisions', ['source_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], name=op.f('fk_watchlist_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_watchlist'))
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=71), nullable=False),
    sa.Column('merkle_batch_id', sa.String(length=36), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name=op.f('fk_evidence_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merkle_batch_id'], ['merkle_batches.batch_id'], name=op.f('fk_evidence_merkle_batch_id_merkle_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_evidence_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_batch', 'evidence', ['merkle_batch_id'], unique=False)
    op.create_index('ix_evidence_event', 'evidence', ['event_id'], unique=False)
    op.create_table('link_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False, comment='pgp_fingerprint | wallet_cluster | stylometry | temporal_overlap | ...'),
    sa.Column('raw_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llr', sa.Numeric(precision=8, scale=4), nullable=False, comment='Log-likelihood ratio for this evidence item'),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('reliability', sa.String(length=1), nullable=True, comment='Admiralty reliability: A-F'),
    sa.Column('credibility', sa.SmallInteger(), nullable=True, comment='Admiralty credibility: 1-6'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['persona_links.link_id'], name=op.f('fk_link_evidence_link_id_persona_links'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_link_evidence_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_evidence'))
    )
    op.create_index('ix_link_evidence_link', 'link_evidence', ['link_id'], unique=False)
    op.create_table('observations',
    sa.Column('obs_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False, comment='extracted | author | recipient | infrastructure'),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], name=op.f('fk_observations_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name=op.f('fk_observations_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('obs_id', name=op.f('pk_observations')),
    sa.UniqueConstraint('event_id', 'entity_id', 'role', name='uq_obs_event_entity_role')
    )
    op.create_index('ix_observations_entity', 'observations', ['entity_id'], unique=False)
    op.create_index('ix_observations_event', 'observations', ['event_id'], unique=False)
    op.create_table('posts',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('handle', sa.String(length=256), nullable=True),
    sa.Column('market', sa.String(length=256), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], name=op.f('fk_posts_actor_id_actors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name=op.f('fk_posts_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', name=op.f('pk_posts'))
    )
    op.create_index('ix_posts_actor', 'posts', ['actor_id'], unique=False)
    op.create_index('ix_posts_handle', 'posts', ['handle'], unique=False)
    op.create_index('ix_posts_market', 'posts', ['market'], unique=False)
    op.create_index('ix_posts_tsv', 'posts', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_tsv', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_market', table_name='posts')
    op.drop_index('ix_posts_handle', table_name='posts')
    op.drop_index('ix_posts_actor', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_observations_event', table_name='observations')
    op.drop_index('ix_observations_entity', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_link_evidence_link', table_name='link_evidence')
    op.drop_table('link_evidence')
    op.drop_index('ix_evidence_event', table_name='evidence')
    op.drop_index('ix_evidence_batch', table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('watchlist')
    op.drop_index('ix_policy_decisions_source', table_name='policy_decisions')
    op.drop_index('ix_policy_decisions_decided_at', table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index('ix_persona_links_band', table_name='persona_links')
    op.drop_index('ix_persona_links_actors', table_name='persona_links')
    op.drop_table('persona_links')
    op.drop_index('ix_infra_onion', table_name='infra_findings')
    op.drop_table('infra_findings')
    op.drop_index('ix_events_source', table_name='events')
    op.drop_index('ix_events_observed_at', table_name='events')
    op.drop_index('ix_events_content_hash', table_name='events')
    op.drop_table('events')
    op.drop_table('actor_entities')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('merkle_batches')
    op.drop_index('ix_entities_normalized', table_name='entities')
    op.drop_index('ix_entities_kind', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_audit_at', table_name='audit_log')
    op.drop_index('ix_audit_actor', table_name='audit_log')
    op.drop_index('ix_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_alerts_type', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_actors_status', table_name='actors')
    op.drop_index('ix_actors_label', table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
